# Dockerfile.prod
FROM node:20-alpine
WORKDIR /app

# 빌드된 결과물만 복사
COPY .output .output
COPY package.json package-lock.json ./
RUN npm install --omit=dev

EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]