services:
  onsen:
    image: onsen:1
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    mem_limit: 4g
    networks:
      - mynet1

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - onsen
    networks:
      - mynet1

networks:
  mynet1:
    driver: bridge